model: "glow_tts"

# model params
num_chars: null
encoder_type: "rel_pos_transformer"
encoder_params:
  kernel_size: 3
  dropout_p: 0.1
  num_layers: 6
  num_heads: 2
  hidden_channels_ffn: 768
use_encoder_prenet: true
hidden_channels_enc: 192
hidden_channels_dec: 192
hidden_channels_dp: 256
dropout_p_dp: 0.1
dropout_p_dec: 0.05
mean_only: true
out_channels: 80
num_flow_blocks_dec: 12
inference_noise_scale: 0.33
kernel_size_dec: 5
dilation_rate: 1
num_block_layers: 4
num_speakers: 0
c_in_channels: 0
num_splits: 4
num_squeeze: 2
sigmoid_scale: false
d_vector_dim: 0

# dataset params
datasets:
  - name: "LJSpeech"
    formatter: "D:\train\audio"

    
# training params
data_dep_init_steps: 10

# inference params
style_wav_for_test: null
inference_noise_scale: 0.0
length_scale: 1.0

# multi-speaker settings
use_speaker_embedding: false
speakers_file: null
use_d_vector_file: false
d_vector_file: false

# optimizer parameters
optimizer: "RAdam"
optimizer_params:
  betas: [0.9, 0.998]
  weight_decay: 1e-6
lr_scheduler: "NoamLR"
lr_scheduler_params:
  warmup_steps: 4000
grad_clip: 5.0
lr: 1e-3

# overrides
min_seq_len: 3
max_seq_len: 500
r: 1  # DO NOT CHANGE - TODO: make this immutable once coqpit implements it.

# testing
test_sentences:
  - "It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent."
  - "Be a voice, not an echo."
  - "I'm sorry Dave. I'm afraid I can't do that."
  - "This cake is great. It's so delicious and moist."
  - "Prior to November 22, 1963."
